package com.iflytek.cachemanager.mapper;

import com.iflytek.cachemanager.entity.Dictionary006;
import com.iflytek.cachemanager.entity.Dictionary006Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Dictionary006Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    long countByExample(Dictionary006Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int deleteByExample(Dictionary006Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int insert(Dictionary006 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int insertSelective(Dictionary006 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    List<Dictionary006> selectByExampleWithRowbounds(Dictionary006Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    List<Dictionary006> selectByExample(Dictionary006Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    Dictionary006 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dictionary006 record, @Param("example") Dictionary006Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dictionary006 record, @Param("example") Dictionary006Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dictionary006 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary006
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictionary006 record);
}