package com.iflytek.cachemanager.mapper;

import com.iflytek.cachemanager.entity.Dictionary003;
import com.iflytek.cachemanager.entity.Dictionary003Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Dictionary003Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    long countByExample(Dictionary003Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int deleteByExample(Dictionary003Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int insert(Dictionary003 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int insertSelective(Dictionary003 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    List<Dictionary003> selectByExampleWithRowbounds(Dictionary003Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    List<Dictionary003> selectByExample(Dictionary003Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    Dictionary003 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dictionary003 record, @Param("example") Dictionary003Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dictionary003 record, @Param("example") Dictionary003Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dictionary003 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary003
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictionary003 record);
}