package com.iflytek.cachemanager.mapper;

import com.iflytek.cachemanager.entity.Dictionary002;
import com.iflytek.cachemanager.entity.Dictionary002Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Dictionary002Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    long countByExample(Dictionary002Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int deleteByExample(Dictionary002Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int insert(Dictionary002 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int insertSelective(Dictionary002 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    List<Dictionary002> selectByExampleWithRowbounds(Dictionary002Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    List<Dictionary002> selectByExample(Dictionary002Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    Dictionary002 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dictionary002 record, @Param("example") Dictionary002Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dictionary002 record, @Param("example") Dictionary002Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dictionary002 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary002
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictionary002 record);
}