package com.iflytek.cachemanager.mapper;

import com.iflytek.cachemanager.entity.slotsobject;
import com.iflytek.cachemanager.entity.slotsobjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface slotsobjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    long countByExample(slotsobjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int deleteByExample(slotsobjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int insert(slotsobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int insertSelective(slotsobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    List<slotsobject> selectByExampleWithRowbounds(slotsobjectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    List<slotsobject> selectByExample(slotsobjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    slotsobject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") slotsobject record, @Param("example") slotsobjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") slotsobject record, @Param("example") slotsobjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(slotsobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(slotsobject record);
}