package com.iflytek.cachemanager.entity;

import java.io.Serializable;

public class slotsobject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slotsobject.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slotsobject.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slotsobject.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slotsobject.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slotsobject.descmsg
     *
     * @mbg.generated
     */
    private Integer descmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slotsobject.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slotsobject
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slotsobject.id
     *
     * @return the value of slotsobject.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slotsobject.id
     *
     * @param id the value for slotsobject.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slotsobject.pid
     *
     * @return the value of slotsobject.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slotsobject.pid
     *
     * @param pid the value for slotsobject.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slotsobject.level
     *
     * @return the value of slotsobject.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slotsobject.level
     *
     * @param level the value for slotsobject.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slotsobject.state
     *
     * @return the value of slotsobject.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slotsobject.state
     *
     * @param state the value for slotsobject.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slotsobject.descmsg
     *
     * @return the value of slotsobject.descmsg
     *
     * @mbg.generated
     */
    public Integer getDescmsg() {
        return descmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slotsobject.descmsg
     *
     * @param descmsg the value for slotsobject.descmsg
     *
     * @mbg.generated
     */
    public void setDescmsg(Integer descmsg) {
        this.descmsg = descmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slotsobject.content
     *
     * @return the value of slotsobject.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slotsobject.content
     *
     * @param content the value for slotsobject.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}